"""create enrolment_documents table

Revision ID: 55f849f3db6b
Revises: b353dd1225f9
Create Date: 2026-08-22 11:07:50.340336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f849f3db6b'
down_revision: Union[str, Sequence[str], None] = 'b353dd1225f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrolment_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrolment_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('original_size', sa.Integer(), nullable=False),
    sa.Column('optimized_size', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('mime_type', sa.String(length=60), nullable=True),
    sa.Column('storage_key', sa.String(length=80), nullable=False),
    sa.Column('quality_status', sa.String(length=20), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['enrolment_id'], ['enrolments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrolment_id', 'document_type', name='uq_document_per_slot')
    )
    with op.batch_alter_table('enrolment_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrolment_documents_enrolment_id'), ['enrolment_id'], unique=False)
        batch_op.create_index('ix_enrolment_documents_status', ['enrolment_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolment_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_enrolment_documents_status')
        batch_op.drop_index(batch_op.f('ix_enrolment_documents_enrolment_id'))

    op.drop_table('enrolment_documents')
    # ### end Alembic commands ###
