"""create enrolments table

Revision ID: b353dd1225f9
Revises: 3c458355a66f
Create Date: 2026-08-22 09:32:26.866868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b353dd1225f9'
down_revision: Union[str, Sequence[str], None] = '3c458355a66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrolments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.String(length=40), nullable=False),
    sa.Column('applicant_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('personal_details', sa.JSON(), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('reference_code', sa.String(length=24), nullable=True),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_code')
    )
    with op.batch_alter_table('enrolments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrolments_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_enrolments_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolments', schema=None) as batch_op:
        batch_op.drop_index('ix_enrolments_user_status')
        batch_op.drop_index(batch_op.f('ix_enrolments_user_id'))

    op.drop_table('enrolments')
    # ### end Alembic commands ###
